steps:
  - name: gcr.io/realtimescoring/mymavengcpcloudbuild
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - '-t'
      - '$_IMAGE_NAME:latest''
      - .
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_GKE_LOCATION'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [   'set',   'image',   'deployment/docimage-created',    'docimage-created=$_IMAGE_NAME:$COMMIT_SHA' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_GKE_LOCATION'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER'
images: [
   '$_IMAGE_NAME:$COMMIT_SHA',
   '$_IMAGE_NAME:latest'
  ]
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_NAMESPACE: default
  _GKE_LOCATION: us-central1-c
  _GKE_CLUSTER: cluster-1
  _IMAGE_NAME: gcr.io/realtimescoring/docimage-created
  _K8S_ANNOTATIONS: gcb-trigger-id=3dcd2a9b-9c07-454d-bb3a-71f3648345e4
  _DOCKERFILE_NAME: Dockerfile
  _K8S_YAML_PATH: k8s/
  _DOCKERFILE_DIR: ''
  _OUTPUT_BUCKET_PATH: realtimescoring_cloudbuild/deploy
  _K8S_LABELS: ''
  _K8S_APP_NAME: first-service
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME