apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pod-name
  name: pod-name
spec:
  replicas: 2
  selector:
    matchLabels:
      run: pod-name
  template:
    metadata:
      labels:
        run: pod-name
    spec:
      containers:
      - image: gcr.io/realtimescoring/docimage-created:$COMMIT_SHA
        name: <app-name>
        ports:
        - containerPort: <container-port>