apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: docimage-created
  name: docimage-created
spec:
  replicas: 2
  selector:
    matchLabels:
      run: docimage-created
  template:
    metadata:
      labels:
        run: docimage-created
    spec:
      containers:
      - image: gcr.io/realtimescoring/docimage-created:latest
        name: docimage-created
        ports:
        - containerPort: 80