apiVersion: apps/v1
kind: Deployment
metadata:
  name: docimage-created
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docimage-created
  template:
    metadata:
      labels:
        app: docimage-created
    spec:
      containers:
      - name: docimage-created
        image: gcr.io/realtimescoring/docimage-created:latest
        ports:
        - containerPort: 80