kind: Service
apiVersion: v1
metadata:
  name: docimage-created-service-yam
spec:
  selector:
     run: docimage-created
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer