apiVersion: "v1"
kind: "Service"
metadata:
  name: "docimage-created-service-yaml"
  namespace: "default"
  labels:
    app: "docimage-created"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "docimage-created"
  type: "LoadBalancer"
  loadBalancerIP: ""